### ISSUE TITLE
scale factor 

### ISSUE THREAD

**Issue by acp29** [ogsteele/Analysis_Scripts#4]
In Clipper you have this line, what is the factor 20000 for? 
`ephysIO(new_filename,S.array(answer*20000:end,:),S.xunit,S.yunit,S.names,S.notes,'int16')`

**Comment by ogsteele** [comment]
Hi @acp29 - please see 7074a10. '20000' referred to the sampling frequency as the inputdlg asked for time in s, but the data is not in seconds.
