### ISSUE TITLE
Adapting to iPSC recordings

### ISSUE THREAD

**Issue by csdias6** [ogsteele/Analysis_Scripts#9]
Hello Dr. Steele,

I'm trying to adapt and use your IStep script for the iPSC-derived neurons. Me and Andy (Penn) were going through my data and we figured out that some of the AQC4 folders were empty (AQC4 crashes sometimes during a recording) and causes the error: 
Error in IStep (line 476)
N=AP_Window(ind_o:ind_o+ind_a)-Base; % period peak-hyper.
The other graphs, such as the AP analysis , membrane excitability and Ih Sag are not affected, it is only the final input resistance calculation and action potential waveform graphs that seem to be affected.
The empty files are often at the end of the recording and the previous recordings still have good results. 
Is it possible to adapt the script to ignore any empty files whilst running the IStep?

Best wishes,
Caden 

[Current clamp data compilation.docx](https://github.com/ogsteele/Analysis_Scripts/files/12320508/Current.clamp.data.compilation.docx)

**Comment by csdias6** [comment]
Additionally, is it possible to also adapt the script to compile the collected data into a spreadsheet?

**Comment by ogsteele** [comment]
Hi Caden, 

Good to speak to you earlier. I've split these errors up into distinct bugs as it makes troubleshooting them, and my resultant documentation, a little cleaner. 

> Additionally, is it possible to also adapt the script to compile the collected data into a spreadsheet?

I have moved the above issue relating to data export to it's own issue #12, and any changes relevant to this will be documented over there. 



> I'm trying to adapt and use your IStep script for the iPSC-derived neurons. Me and Andy (Penn) were going through my data and we figured out that some of the AQC4 folders were empty (AQC4 crashes sometimes during a recording) and causes the error: Error in IStep (line 476) N=AP_Window(ind_o:ind_o+ind_a)-Base; % period peak-hyper. The other graphs, such as the AP analysis , membrane excitability and Ih Sag are not affected, it is only the final input resistance calculation and action potential waveform graphs that seem to be affected. The empty files are often at the end of the recording and the previous recordings still have good results. Is it possible to adapt the script to ignore any empty files whilst running the IStep?

I have then created a seperate issue relating to accepting missing data in issue #13, and again any changes will be done over there. 

I'll close this issue now as these are all documented as seperate issues. Any further bugs pop up, please let me know by creating a new issue with the behaviour necessary to create the issue and the error message produced. 

Looking forward to working with you on this! 

Cheers, 
O
